const POWER_OFF_CONFRIMED_MUTATION = 'POWER_OFF_CONFRIMED_MUTATION';
const POWER_OFF_STATE = 'POWER_OFF_STATE'
const LOCK_STATE = 'LOCK_STATE'
const SET_IS_UNLOCK_REQUESTED = 'SET_IS_UNLOCK_REQUESTED'
const SET_IS_BLACK_SCREEN = 'SET_IS_BLACK_SCREEN'
const UPDATE_PAGESTACK = 'UPDATE_PAGESTACK'
const UPDATE_PICTURES = 'UPDATE_PICTURES'

export default {
    POWER_OFF_CONFRIMED_MUTATION,
    POWER_OFF_STATE,
    LOCK_STATE,
    SET_IS_UNLOCK_REQUESTED,
    SET_IS_BLACK_SCREEN,
    UPDATE_PAGESTACK,
    UPDATE_PICTURES
}
